version: "3.6"

services:

  nginx:
    image: nginx:alpine
    platform: linux/amd64
    working_dir: /opt/front
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./app:/var/www
    ports:
      - ${APP_PORT}:80